### ISSUE TITLE
Convert svg's "opacity" field into "strokeAlpha" and "fillAlpha" on Android

### ISSUE THREAD

**Issue by asarazan** [inloop/svg2android#1]
Was really pleased at how easy and functional this tool is, the only thing that came out wrong is the opacity for a shine effect, the opacity data seems to have been discarded.

Thanks!

**Comment by yuraj11** [comment]
Thanks for feedback, I have implemented only fill-opacity and stroke-opacity propetries but after looking into w3 svg documentation - yeah there is an opacity property which is not implemented. I will add It.
