### ISSUE TITLE
Why white color in SVG was converted to black color in VectorDrawable?

### ISSUE THREAD

**Issue by juliakvashyna** [inloop/svg2android#16]
Sorry, if I ask this question in wrong place.

**Comment by pvolyntsev** [comment]
Could you please attach the sample of your SVG file?

**Comment by juliakvashyna** [comment]
Thanks for reply! SVG files are in attachment

2015-07-27 22:42 GMT+03:00 Pavel Volyntsev notifications@github.com:

**Comment by martyglaubitz** [comment]
this issue may be related to this issue: #17

**Comment by yuraj11** [comment]
Could you please upload SVG file If possible or send me PM ?

**Comment by davekover** [comment]
I am seeing a similar issue. Image exported from Illustrator:

https://drive.google.com/file/d/0B-GALEho0NVHM0g0LU1xYW15WlE/view?usp=sharing

After putting through svg2android, the android:fillcolor is #000000

Edit: Looks like my files are using the CSS based colors, as seen in issue #17. I'm not sure if the original reporter was outputting files with the same format.

**Comment by yuraj11** [comment]
Yes, this is next next thing I will fix, this should be easy fix.

**Comment by yuraj11** [comment]
https://github.com/inloop/svg2android/issues/17
