### ISSUE TITLE
<New feature request > We need reverse convert xml2svg sometimes.

### ISSUE THREAD

**Issue by jane00** [inloop/svg2android#19]
Does it possible to do the reverse work？

**Comment by yuraj11** [comment]
I thought about this feature but what would be the real reason for this? Anyone else would use this ? Anyone could then "stole" indirectly SVGs from others project.

**Comment by davekover** [comment]
You can just copy the point data from an XML and place it into an SVG and accomplish the task manually. Adding the reverse method would just save someone time from having to do it by hand.

**Comment by jane00** [comment]
Thanks very much for your reply. The reason is like this: sometimes we need convert reverse just for checking whether the icon is right.
And, for these two weeks, we found another problem. The converted xml icon is displayed correctly on Android 5.1.1. But, on 5.0.2, the same xml icon file is displayed with defect or disappeared.

example:

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <path
        android:fillColor="#000000"
        android:pathData="M17.7,7.7L12,2h-1v7.6L6.4,5L5,6.4l5.6,5.6L5,17.6L6.4,19l4.6-4.6V22h1l5.7-5.7L13.4,12L17.7,7.7z M13,5.8l1.9,1.9L13,9.6 V5.8z M14.9,16.3L13,18.2v-3.8L14.9,16.3z" />
</vector>
```

**Comment by jane00** [comment]
I'm sorry the example code above is displayed wrong by github

**Comment by jaredrummler** [comment]
Looking for this too. +1 :P

**edit**: I wrote a simple class to do this: https://github.com/jaredrummler/vector2svg

**Comment by yuraj11** [comment]
Maybe It's not bad idea but I am thinking that this will not work every time. When you make a svg and group all shapes into one and then export to svg and convert to vectordrawable - reverse job will work but you will be not able to edit svg by individual elements.
BTW And also this should be a new github project or fork of this to prevent mess in code.

**Comment by yuraj11** [comment]
Use this https://github.com/jaredrummler/vector2svg
