### ISSUE TITLE
Add batch (multi-svg) capabilities

### ISSUE THREAD

**Issue by davekover** [inloop/svg2android#20]
I'm working with large amounts of SVGs and would love to be able to drag a set of files and download them all at once. I think it'd be optimal for this option to automatically download the resulting files and not display the output as it would normally.

Let me add that I've found this tool to be invaluable to my work and I'm quite thankful that you've made this available. Cheers!

**Comment by yuraj11** [comment]
Thanks! I am glad that you find this tool useful. I am working on this feature: 
![clipboard02](https://cloud.githubusercontent.com/assets/5477518/9861555/4d5a1636-5b33-11e5-94e2-487f1a212ea0.png)

Also I think the best way to export multiple files will be to ZIP them into one file.

**Comment by davekover** [comment]
I was thinking that a zip file might be a way to handle the result - glad we're on the same page! Thanks so much for taking this feature request. :)

**Comment by yuraj11** [comment]
Ok, It's done https://github.com/inloop/svg2android/commit/646797295e78fa6d63bf881f8d9c714c29fb19b6 . I have tried 362 files (total size 130 kB) at once - It generated code and ZIP file almost immediately (but still If you have big SVG files there could be some performance problem - large lag). Please tell me how It works for you, thanks!
BTW: It will append file `log.html` into ZIP, so you can check there for errors/warnings.

**Comment by davekover** [comment]
I tested with a few different batch sizes. 100+ files at 1.1mb total size, 30 items at 377kb, etc. I haven't seen any issues with output. I did spot a path name issue, but I'll file that separately as I don't believe it's related to the multi-file functionality.

This looks to be working as envisioned. Thanks for adding the feature!

**Comment by conrad-heimbold** [comment]
Is there a command line interface for this functionality? 
I would like to convert the icons from my terminal, not in a browser...
