### ISSUE TITLE
Byte order mark being prepended to xml

### ISSUE THREAD

**Issue by Danm72** [inloop/svg2android#22]
When inputting the below xml a "< feff >" is prepended to the output file, which then will not render in Android studio. U+FEFF is the code point for a byte order mark. This might be from a dodgey conversion between iso-8859 and utf8. http://stackoverflow.com/questions/1972362/why-is-my-bash-script-adding-feff-to-the-beginning-of-files

![screen shot 2015-09-22 at 10 42 32](https://cloud.githubusercontent.com/assets/1926968/10015192/b50cade6-6116-11e5-8d5e-74040593ab8c.png)

SVG: https://gist.github.com/Danm72/9c87a303d0bd4b3245da

**Comment by yuraj11** [comment]
Hm, what browser do you use (and version) and OS? Does It happen on other files too? Could you try some other SVG (downloaded from somewhere else) ?

**Comment by Danm72** [comment]
Hey, sorry I should have included the browser version!

Chrome stable release Version 45.0.2454.93 (64-bit), OSX 10.10.5(Yosemite Stable).

I haven't seen it happen on other SVGs I've used, it could just be a crappy xml. Just wanted to make you aware of it!

**Comment by yuraj11** [comment]
Could you upload original SVG file? So I can test It.

**Comment by Danm72** [comment]
Its in the gist I included above! https://gist.github.com/Danm72/9c87a303d0bd4b3245da

**Comment by yuraj11** [comment]
Yes but I mean If you could upload that svg somewhere else because gist.github does not contain original file encoding. Thanks for help.

**Comment by Danm72** [comment]
### ooops

https://drive.google.com/file/d/0By11uJLBmfN1NVNXR1p2c2cxakU/view?usp=sharing Hope that helps

**Comment by yuraj11** [comment]
I do not see any problem in that document, I've opened mask_0007.xml in notepad++ with option Show all symbols and I do not see any problem.

**Comment by yuraj11** [comment]
Should be fixed now, could you try It now?
