### ISSUE TITLE
Line 1: PI must not start with xml (position:unknown ﻿@1:5)

### ISSUE THREAD

**Issue by CordasIgor** [inloop/svg2android#24]
If I leave <?xml version="1.0" encoding="utf-8"?> at the top of the file I get the exception listed in the description. I am using sdk 21

**Comment by yuraj11** [comment]
Looks like problem with file encoding, must look on this (also similiar to this #22)

**Comment by yuraj11** [comment]
How did you save exported XML ? By Download button or by Select all and then creating manually file? Make sure your file is encoded by UTF-8.

**Comment by CordasIgor** [comment]
It works if I delete the first line. I used the download button to get the
file.

**Comment by yuraj11** [comment]
I have checked now, exported file is encoded in utf-8, could you confirm If It is in utf-8 when you open It e.g. in notepad++ ? Do your android project use utf-8 encoding? http://tools.android.com/knownissues/encoding

**Comment by CordasIgor** [comment]
It says UTF-8 BOM in Notepad++. MY Android studio project is also setup to
use UTF8.

On Sun, Oct 11, 2015 at 1:38 PM, Juraj Novák notifications@github.com
wrote:

> I have checked now, exported file is encoded in utf-8, could you confirm
> If It is in utf-8 when you open It e.g. in notepad++ ? Do your android
> project use utf-8 encoding? http://tools.android.com/knownissues/encoding
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inloop/svg2android/issues/24#issuecomment-147184964.

## 

_Deploy_
Igor Čordaš / Android Developer
icordas@deployinc.com
www.deployinc.com

**Comment by yuraj11** [comment]
Could you try It now? I've disabled prepending byte order mark in exported XML files.
