### ISSUE TITLE
"Problem during parsing svg (flatten failed)" all times

### ISSUE THREAD

**Issue by jrizzoli** [inloop/svg2android#31]
I've been unable to use this tool for some days since Chrome 48 update, it always reports "Error: problem during parsing svg (flatten failed)." for each file i use, even those i've already used with this tool. With firefox I don't have this issue.

**Comment by yuraj11** [comment]
Please check developer console in chrome (F12->Console) and paste error here, thanks!

**Comment by jrizzoli** [comment]
TypeError: pathDOM.getTransformToElement is not a function(…)generateCode @ main.js?v=20:1

**Comment by yuraj11** [comment]
Yes, I have checked changelog of chrome 48 and function getTransformToElement was removed from chrome :( I will investigate this and try find solution.

**Comment by yuraj11** [comment]
Ok, should be fixed now :) Update your page F5 or Ctrl+F5 to refresh & clear page cache. Let me now If It works for you now.

**Comment by jrizzoli** [comment]
Works, thank you. I really like this tool. Have a nice day
