### ISSUE TITLE
Ellipses turn into figure eights

### ISSUE THREAD

**Issue by crazystairs** [inloop/svg2android#34]
See attached .png files.

Converting ellipses into paths and then converting the containing SVG into an XML seems to rotate, duplicate and join the shapes.

![exported_from_inkscape](https://cloud.githubusercontent.com/assets/5713596/13156774/6d5a3eee-d684-11e5-9ae6-50ba0b1436aa.png)

![generated_by_android_studio_from_android2svg-xml](https://cloud.githubusercontent.com/assets/5713596/13156775/6d6005ae-d684-11e5-8be7-d96b7711ce7a.png)

[2ellipses.svg.txt](https://github.com/inloop/svg2android/files/136860/2ellipses.svg.txt) (Renamed to .txt to circumvent upload restrictions)

**Comment by crazystairs** [comment]
This problem seems to coincide with the warning about "scientific E notation" I get - oddly enough only when unchecking "Bake transforms into paths".

I got rid of the warning by increasing Inkscape's output precision.

**Comment by crazystairs** [comment]
The problem only occurs with "Bake transforms into paths" checked.

**Comment by yuraj11** [comment]
Looks like It has been fixed with change https://github.com/inloop/svg2android/commit/4f524423debaf9814f30b3609d428f1bbb77e674
