### ISSUE TITLE
Bug: "null" instead of "@null" ?  

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [inloop/svg2android#36]
using this SVG as an input:

```
<svg width="476" height="476" xmlns="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <ellipse ry="198.5" rx="198.5" id="svg_3" cy="238" cx="238" stroke-linecap="null" stroke-linejoin="null" stroke-width="0" stroke="#000000" fill="#f3f3f3"/>
 </g>
</svg>
```

will create this:

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="476dp"
    android:height="476dp"
    android:viewportWidth="476"
    android:viewportHeight="476">

    <path
        android:fillColor="#f3f3f3"
        android:strokeColor="#000000"
        android:strokeLineJoin="null"
        android:strokeLineCap="null"
        android:pathData="M 238 39.5 C 347.628522841 39.5 436.5 128.371477159 436.5 238 C 436.5 347.628522841 347.628522841 436.5 238 436.5 C 128.371477159 436.5 39.5 347.628522841 39.5 238 C 39.5 128.371477159 128.371477159 39.5 238 39.5 Z" />
</vector>
```

but Android studio can't handle the nulls.

**Comment by AndroidDeveloperLB** [comment]
Anyway, I think that if the stroke width is 0, all stroke-related stuff should be removed, because it doesn't need to get drawn.

**Comment by yuraj11** [comment]
That's not an ordinary svg - also not sure If valid one with null values.

**Comment by AndroidDeveloperLB** [comment]
Well, I'm not an expert in SVG, but the web browser showed it fine, and it was created via an online SVG editor :
http://svg-edit.googlecode.com/svn-history/r1771/trunk/editor/svg-editor.html

**Comment by yuraj11** [comment]
Fixed

**Comment by AndroidDeveloperLB** [comment]
Thank you.
Say, do you know perhaps if Google is working on such a conversion tool?

**Comment by yuraj11** [comment]
There is Vector Asset Studio in Android Studio but It is not good as this tool. Maybe in future.

**Comment by AndroidDeveloperLB** [comment]
Isn't it a tool that only takes vectors, and create images out of them?

**Comment by yuraj11** [comment]
No It generates VectorDrawable xml.

**Comment by AndroidDeveloperLB** [comment]
It does?!
From SVG ?
How do you use it?
And what's not good in it?
Odd that I never heard about it.
