### ISSUE TITLE
No shape elements found in svg.

### ISSUE THREAD

**Issue by ThanosFisherman** [inloop/svg2android#37]
Trying to convert my svg file into xml drawable but getting this error. Already tried with build in android studio converter but got "premature end of file" error. Could there be something wrong with my svg file?

**Comment by yuraj11** [comment]
Could you send me that svg?

**Comment by ThanosFisherman** [comment]
Hey @yuraj11 here you go. Just change the file ending from .png to .svg
![wifisherlock_icon svg](https://cloud.githubusercontent.com/assets/4888330/13918572/008198f2-ef71-11e5-84e6-0ab87c30a0eb.png)

**Comment by yuraj11** [comment]
This one has raster image inside svg (open in text editor and you will see very long base64 image). Maybe you can try vectorize this image in some editor (inkscape has this option).

**Comment by ThanosFisherman** [comment]
You are right! Thanks for letting me know. Actually the whole thing was extracted from photoshop as svg and then imported to inkscape. I will see what I can do. Thanks again
