### ISSUE TITLE
No shape elements found in svg

### ISSUE THREAD

**Issue by happycodinggirl** [inloop/svg2android#39]
i use Inkscape to convert png to svg ,and then to get VectorDrawable,but it says No shape elements found in svg

**Comment by yuraj11** [comment]
https://github.com/inloop/svg2android/issues/37
I should add more descriptive error.

**Comment by yuraj11** [comment]
https://github.com/inloop/svg2android/commit/618f144c8ba7d3489163a873ab0d6554cf2e43b9
