### ISSUE TITLE
Incorrect output

### ISSUE THREAD

**Issue by yelinaung** [inloop/svg2android#41]
It seems the vector drawable output of this file seems incorrect. I am sorry that the file is big and I attached it in the zip ( ~ 400 KB )

[buildings-x414.svg.zip](https://github.com/inloop/svg2android/files/192856/buildings-x414.svg.zip)

And the output is

![layout-2016-03-29-123406](https://cloud.githubusercontent.com/assets/275120/14098075/9449c6d8-f5aa-11e5-8960-47fb9b07d4a9.png)

**Comment by yuraj11** [comment]
Thanks for reporting, I'll have a look at it.

**Comment by yuraj11** [comment]
https://github.com/inloop/svg2android/issues/44
