### ISSUE TITLE
Extra (incorrect) vertical paths at the end 

### ISSUE THREAD

**Issue by yelinaung** [inloop/svg2android#42]
Like #41, there seems to be extra vertical lines at the end. The input is 
[alerts.svg.zip](https://github.com/inloop/svg2android/files/193046/alerts.svg.zip)

And the output 
![bell xml - 99-android-v2 - work 99 99-android-v2 - android studio 2 1 preview 4 2016-03-29 15-46-23](https://cloud.githubusercontent.com/assets/275120/14101200/71b5246c-f5c5-11e5-8f22-865d725c7f2c.png)

Thanks for the awesome tool!

**Comment by yuraj11** [comment]
Looks like problem in how is VectorDrawable rendered. I can't fix It. Try some manual changes in editor.
