### ISSUE TITLE
Incorrect Output of Hollow Path

### ISSUE THREAD

**Issue by grote** [inloop/svg2android#43]
Have a look at this simple SVG:

![example](https://cloud.githubusercontent.com/assets/244947/14288547/8a84ea32-fb2d-11e5-8063-41e6d649eed9.png)

``` svg
?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   id="svg2367"
   height="745"
   width="745"
   version="1.0">
  <path
     id="path96"
     d="M 355.21871,93.556599 C 752.92565,85.659375 747.15567,748.84406 452.37064,739.7049 4.6716594,741.05072 4.3263198,102.72878 355.21871,93.556599 Z M 189.41544,361.6496 c 96.89558,-9.6305 273.82424,-24.26663 370.54595,-35.511 L 432.78971,606.03793"
     style="fill:#ec1b2d;fill-rule:evenodd;stroke:none" />
</svg>
```

When transforming this, into an Android VectorDrawable, the white triangle in the middle is lost.

Is this a bug in your awesome tool or a limitation of VectorDrawables?

**Comment by yuraj11** [comment]
It has unsupported "fill-rule:evenodd" attribute, https://github.com/inloop/svg2android/issues/44

**Comment by grote** [comment]
Thanks for pointing me into the right direction! :smile:

I found these instructions that can be used to convert the problematic paths as a work-around:
https://github.com/a-student/SvgToVectorDrawableConverter#manual-editing

**Comment by yuraj11** [comment]
Yeah, It will be much easier to fix this in vector editor for now. VectorDrawable is very lightweight version of SVG in Android and still missing many features from a real SVG specification.
