### ISSUE TITLE
Converted but getting build error within android studio

### ISSUE THREAD

**Issue by emartynov** [inloop/svg2android#45]
Attached file
[icon_security.svg.zip](https://github.com/inloop/svg2android/files/209973/icon_security.svg.zip)

**Comment by yuraj11** [comment]
Too much complicated svg, clipPath (+evenodd/nonzero cliprule) and rgb() colors are not supported. Try editing file manually to get rid of those things.

**Comment by emartynov** [comment]
Should I close issue since it is known? Or more action with it can be done

**Comment by yuraj11** [comment]
You should try to correct svg in your editor.
