### ISSUE TITLE
Error: 1:app:mergeDebugResources FAILED

### ISSUE THREAD

**Issue by lukeallison** [inloop/svg2android#46]
I haven't had any luck using any SVGs produced from this app in an Android project. These include those supplied on the google material icons page. 

Android Studio to 2.1
compileSdkVersion 23
buildToolsVersion "23.0.2"
minSdkVersion 14
targetSdkVersion 23

**Comment by yuraj11** [comment]
Please can you paste entire error ? "app:mergeDebugResources FAILED" is general error.

**Comment by lukeallison** [comment]
Sorry, I answered my issue here:
http://stackoverflow.com/questions/36906986/why-is-my-svg-failing-to-load-in-vector-asset-studio/37337205#37337205 

Inkscape was the issue.
