### ISSUE TITLE
Image being rotated by 90 degres after conversion

### ISSUE THREAD

**Issue by KanthWasTaken** [inloop/svg2android#49]
Hi, i can't figure out why my SVG is rotated after the conversion.
Here my SVG :
`<?xml version="1.0" encoding="UTF-8"?>
<svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:cc="http://creativecommons.org/ns#"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:svg="http://www.w3.org/2000/svg" viewBox="0 0 205.99126 255.61626" height="255.61626" width="205.99126" xml:space="preserve" version="1.1" id="svg2">
    <metadata id="metadata8">
        <rdf:RDF>
            <cc:Work rdf:about="">
                <dc:format>image/svg+xml</dc:format>
                <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
            </cc:Work>
        </rdf:RDF>
    </metadata>
    <defs id="defs6">
        <clipPath id="clipPath16" clipPathUnits="userSpaceOnUse">
            <path id="path18" d="m 0,204.493 164.793,0 L 164.793,0 0,0 0,204.493 Z" />
        </clipPath>
        <clipPath id="clipPath28" clipPathUnits="userSpaceOnUse">
            <path id="path30" d="m 19.2131,188.26 126.3599,0 0,-126.36 -126.3599,0 0,126.36 z" />
        </clipPath>
    </defs>
    <g transform="matrix(1.25,0,0,-1.25,0,255.61625)" id="g10">
        <g id="g12">
            <g clip-path="url(#clipPath16)" id="g14">
                <g transform="translate(82.3966,196.6886)" id="g20">
                    <path id="path22" style="fill:#2532c4;fill-opacity:1;fill-rule:nonzero;stroke:none" d="m 0,0 c -39.573,0 -71.609,-32.036 -71.609,-71.609 0,-33.92 23.556,-62.187 55.12,-69.725 L 0,-188.681 l 16.489,47.347 c 31.565,7.538 55.12,35.805 55.12,69.725 C 71.609,-32.036 39.573,0 0,0" />
                </g>
                <g id="g24">
                    <g id="g26" />
                    <g id="g32">
                        <g id="g34" clip-path="url(#clipPath28)">
                            <g id="g36" transform="translate(82.3931,188.26)">
                                <path id="path38" style="fill:#ffffff;fill-opacity:1;fill-rule:nonzero;stroke:none" d="m 0,0 c 34.91,0 63.18,-28.28 63.18,-63.18 0,-34.9 -28.27,-63.18 -63.18,-63.18 -34.9,0 -63.18,28.28 -63.18,63.18 C -63.18,-28.28 -34.9,0 0,0" />
                            </g>
                        </g>
                    </g>
                </g>
                <g transform="translate(119.6754,103.0849)" id="g40">
                    <path id="path42" style="fill:#2532c4;fill-opacity:1;fill-rule:nonzero;stroke:none" d="m 0,0 -36.752,0 -36.752,0 c -1.475,0 -3.791,0.211 -3.686,2.317 0.105,2.001 1.895,3.264 1.895,3.264 L -36.752,27.906 1.685,5.581 c 0,0 1.79,-1.263 2.001,-3.264 C 3.791,0.316 1.474,0 0,0 M 8.635,6.95 C 5.897,9.688 -33.909,33.066 -34.33,33.277 l -0.211,0.105 0,4.002 0.106,0.105 c 0.526,0.527 1.158,0.948 1.79,1.475 2.843,2.316 6.318,5.16 6.318,10.425 0,6.424 -5.16,11.584 -11.584,11.584 -6.634,0 -11.583,-4.739 -11.583,-11.057 0,-0.948 0.316,-1.791 0.737,-2.422 0.632,-0.843 1.579,-1.159 2.948,-1.054 2.001,0.211 2.317,2.107 2.317,4.107 l 0,0.527 c 0.105,1.58 2.528,4.002 5.581,4.002 3.16,0 5.792,-2.528 5.792,-5.687 0,-3.054 -0.632,-4.318 -4.844,-6.424 -2.001,-0.947 -3.054,-2.001 -3.054,-4.528 l 0.106,-5.055 -0.316,-0.105 C -40.649,33.066 -80.455,9.688 -83.193,6.95 c -1.474,-1.474 -2.106,-5.476 -0.737,-8.74 0.843,-2.001 2.633,-4.318 6.74,-4.318 l 79.823,0 c 4.107,0 5.897,2.317 6.739,4.318 1.369,3.264 0.737,7.266 -0.737,8.74" />
                </g>
            </g>
        </g>
    </g>
</svg>`

And here the file after conversion : 
`<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="205.99126dp"
    android:height="255.61626dp"
    android:viewportWidth="205.99126"
    android:viewportHeight="255.61626">
    <path
        android:fillColor="#2532c4"
        android:pathData="M102.996,9.75551 C53.5295,9.75551,13.4845,49.8005,13.4845,99.2668
C13.4845,141.667,42.9295,177.001,82.3845,186.423 L102.996,245.607
L123.607,186.423 C163.063,177.001,192.507,141.667,192.507,99.2668
C192.507,49.8005,152.462,9.75551,102.996,9.75551" />
    <path
        android:fillColor="#ffffff"
        android:pathData="M102.991,20.2913 C146.629,20.2913,181.966,55.6413,181.966,99.2663
C181.966,142.891,146.629,178.241,102.991,178.241
C59.3664,178.241,24.0164,142.891,24.0164,99.2663
C24.0164,55.6413,59.3664,20.2913,102.991,20.2913" />
    <path
        android:fillColor="#2532c4"
        android:pathData="M149.594,126.76 L103.654,126.76 L57.7143,126.76
C55.8705,126.76,52.9755,126.496,53.1067,123.864
C53.238,121.363,55.4755,119.784,55.4755,119.784 L103.654,91.8776
L151.701,119.784 C151.701,119.784,153.938,121.363,154.202,123.864
C154.333,126.365,151.437,126.76,149.594,126.76 M160.388,118.073
C156.965,114.65,107.208,85.4276,106.682,85.1639 L106.418,85.0326
L106.418,80.0301 L106.55,79.8989
C107.208,79.2401,107.998,78.7139,108.788,78.0551
C112.342,75.1601,116.686,71.6051,116.686,65.0239
C116.686,56.9939,110.236,50.5439,102.205,50.5439
C93.913,50.5439,87.7268,56.4676,87.7268,64.3651
C87.7268,65.5501,88.1217,66.6039,88.648,67.3926
C89.438,68.4464,90.6217,68.8414,92.333,68.7101
C94.8343,68.4464,95.2292,66.0764,95.2292,63.5764 L95.2292,62.9176
C95.3605,60.9426,98.3893,57.9151,102.205,57.9151
C106.156,57.9151,109.446,61.0751,109.446,65.0239
C109.446,68.8414,108.656,70.4214,103.39,73.0539
C100.889,74.2376,99.573,75.5551,99.573,78.7139 L99.7055,85.0326 L99.3105,85.1639
C98.783,85.4276,49.0255,114.65,45.603,118.073
C43.7605,119.915,42.9705,124.918,44.6817,128.998
C45.7355,131.499,47.973,134.395,53.1067,134.395 L152.885,134.395
C158.019,134.395,160.257,131.499,161.309,128.998
C163.02,124.918,162.23,119.915,160.388,118.073" />
</vector>`

To be clear the output on my application looks like that : 
![screenshot 12 mai 2016 14-30-58](https://cloud.githubusercontent.com/assets/8203554/15214649/8653d46c-184e-11e6-96ed-eeffb48a819c.png)

Do you have any ideas to fix this behaviour ?

Thanks in advance !

**Comment by KanthWasTaken** [comment]
Just to be clear, i'm pretty new to SVG integration in Android and seeing the Android Vector Asset software unable to import my SVG i tried your service. I hope you can help me understand why i can't get my icons in the right position ! :)

**Comment by yuraj11** [comment]
This because google maps rotate markers not problem of vectordrawable.
