### ISSUE TITLE
android:strokeWidth="1" missing in all paths

### ISSUE THREAD

**Issue by guidedways** [inloop/svg2android#51]
It seems no matter what SVG I try and convert, it misses out this one key tag:

android:strokeWidth="1"

And due to this, the produced SVG is extremely 'thin'. Not sure if it's the SVG or the tool, but either way it should perhaps put this into each path automatically perhaps? I've uploaded a sample file.

[taskCheckmarkNormal.svg.zip](https://github.com/inloop/svg2android/files/288222/taskCheckmarkNormal.svg.zip)

**Comment by yuraj11** [comment]
Thanks to gyoda, this should be fixed now!
