### ISSUE TITLE
converted files are truncated

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [inloop/svg2android#55]
I tried to convert some files, but they failed to be converted well.
It wrote to me :

Warning: transforms on path are not supported, use option Bake transforms into path

I tried to enable it, but then it didn't convert at all.

Attached a sample SVG file.

[google_plus.zip](https://github.com/inloop/svg2android/files/345820/google_plus.zip)

What can I do to fix it? Is there anything I should tell the designer about what to do on Illustrator ?

**Comment by yuraj11** [comment]
Hm, works fine for me, what web browser do you use? Try Google Chrome.

**Comment by AndroidDeveloperLB** [comment]
It happens on Chromium 54.0.2794.0 (64-bit) , Maxthon 4.9.3.1000 , Chrome  53.0.2785.21 dev-m .

Correction: after enabling the checkbox, it works.
Odd. Maybe it occurs only for one of those web browsers.
I thought the conversion is done on the server.

**Comment by yuraj11** [comment]
But can you convert It at all or It is only wrongly rendered in Android? The weird thing is that in Android Studio preview It looks perfect but when I run It is skewed.
