### ISSUE TITLE
Wrongly converted SVG "srfinfohd.default.svg"

### ISSUE THREAD

**Issue by warped-ch** [inloop/svg2android#56]
Converted "srfinfohd.default.svg" to "srf_info_hd.xml". Preview in Android Studio v2.1.2, API 24 looks like something went wrong, please see "AndroidStudioPreview_srfinfohd.default.png" for details.

The mentioned files can be found here:
[srfinfohd.zip](https://github.com/inloop/svg2android/files/350567/srfinfohd.zip)

**Comment by yuraj11** [comment]
With option "Bake transforms into path" It looks fine. Try It.
