### ISSUE TITLE
Does not work with reference SVG from Wikipedia

### ISSUE THREAD

**Issue by martinadamek** [inloop/svg2android#63]
I have tried to download https://en.wikipedia.org/wiki/File:SVG_logo.svg and then drag & drop it on Mac to Chrome and it ends with error message 'No shape elements found in svg.'

**Comment by yuraj11** [comment]
It is because of this:
`<a xlink:href="http://www.w3.org/Graphics/SVG/" target="_parent" xlink:title="W3C SVG Working Group home page"> ..... </a>` 
Entire SVG structure is nested in a href link. 99% of SVGs will be not as this one but I can fix this.

**Comment by yuraj11** [comment]
Fixed in https://github.com/inloop/svg2android/commit/d0f0b4ff4855d81d5008087da021b812086b90ee
