### ISSUE TITLE
Wrong rotations in conversion of SVG

### ISSUE THREAD

**Issue by urizev** [inloop/svg2android#64]
I think this is due to rotations.

https://en.wikipedia.org/wiki/Flag_of_Antigua_and_Barbuda#/media/File:Flag_of_Antigua_and_Barbuda.svg

<img width="731" alt="captura de pantalla 2016-09-16 a las 7 17 16" src="https://cloud.githubusercontent.com/assets/997364/18576003/a23d1efc-7bdd-11e6-8b23-32190b484d3c.png">

But got

<img width="376" alt="captura de pantalla 2016-09-16 a las 7 18 23" src="https://cloud.githubusercontent.com/assets/997364/18576022/d1d16042-7bdd-11e6-9a07-037e74782ea9.png">

**Comment by yuraj11** [comment]
Just use option `Bake transforms into path` and you should get correct output.

**Comment by urizev** [comment]
Works perfectly thanks!

**Comment by soshial** [comment]
@yuraj11, where is this functionality located?

**Comment by yuraj11** [comment]
![image](https://cloud.githubusercontent.com/assets/5477518/24914550/d9db3872-1ed4-11e7-8770-f0b9aebf533b.png)
