### ISSUE TITLE
failed converting svg with transform function 

### ISSUE THREAD

**Issue by boes13** [inloop/svg2android#68]
this issue is highly probably similar with #67 , but my svg is quite simple (no dependency to other library) to start solving the bigger issue.

svg code below is painting image of text "1.1":

```
<svg viewBox="0 0 2612 2048" style="height: 36px;" fill="gray">
    <path d="M100 518v419q0 248 116 394t311 146t312 -145.5t117 -394.5v-419q0 -250 -116.5 -394.5t-310.5 -144.5q-195 0 -312 144.5t-117 394.5zM305 490q0 -165 59 -261t165 -96t163.5 95.5t57.5 261.5v476q0 165 -58.5 260t-164.5 95t-164 -95t-58 -260v-476z" transform="scale(1,-1) translate(0,-1536)"/>
    <path d="M138 0v203h205v-203h-205z" transform="scale(1,-1) translate(1056,-1536)"/>
    <path d="M100 518v419q0 248 116 394t311 146t312 -145.5t117 -394.5v-419q0 -250 -116.5 -394.5t-310.5 -144.5q-195 0 -312 144.5t-117 394.5zM305 490q0 -165 59 -261t165 -96t163.5 95.5t57.5 261.5v476q0 165 -58.5 260t-164.5 95t-164 -95t-58 -260v-476z" transform="scale(1,-1) translate(1556,-1536)"/>
</svg>
```

the resulting image converting this to android resource is a half upside down image of "1.1".

**Comment by yuraj11** [comment]
Hm, this is not a valid svg I can't even open It in Chrome. Could you repost that svg?

**Comment by boes13** [comment]
you can use image viewer. to view the file on web browser (chrome, firefox), just add arguments to the svg opening tag as below:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 2612 2048" style="height: 36px;" fill="gray">`

**Comment by yuraj11** [comment]
Works fine for me with option "Bake transforms into path", but there is "0.0" not "1.1"

**Comment by boes13** [comment]
omg, you're right, i did not notice the option bake transform back then. and personally have no idea if you have transform on path you should enable that option.
thank you, it's a false alarm
