### ISSUE TITLE
Doesn't support viewBoxes with a non-zero left or top

### ISSUE THREAD

**Issue by teslacoil** [inloop/svg2android#7]
If you have an SVG with a non-zero left/top viewBox:

```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
 viewBox="420 0 1080 1080"
```

The viewBox is interpreted the same as `viewBox="0 0 1080 1080"` so the final asset will be offset within it's viewport. (viewBox coordinates are `x y width height`, so the 1080 is still the correct width and height, we're just offset)

As Android's VectorDrawable doesn't support an offset, svg2android should either offset the path data appropriately or display a warning so the user knows they need to adjust the viewbox and upload again.

**Comment by yuraj11** [comment]
x and y are discarded for now, It's min-x min-y width height (http://www.w3.org/TR/SVG/coords.html#ViewBoxAttribute), I think there should be always warning when minx or miny != 0 .. It's possible to wrap path into group and set translateX/Y but not sure If this has practical usage ? , warning should be enough.

**Comment by teslacoil** [comment]
I think just a warning is enough. I ran into the issue because my designer exported an SVG that way, once we realized what the issue was it was easy enough for him to change it on his end and export an SVG that starts at 0, 0
