### ISSUE TITLE
Missing l for relative coordinates

### ISSUE THREAD

**Issue by peterrosell** [inloop/svg2android#71]
I converted a svg file that I have created from Inkscape. Exported it as plain svg. When converting it I got an invalid image. I studied the output a bit and noticed that a l (small letter L) is missing on several pathes.

Original file: https://github.com/peterrosell/svg2android/blob/gh-pages/scale%20logo_plain.svg
Bad vector file: https://github.com/peterrosell/svg2android/blob/gh-pages/scale_logo_bad.xml
Corrected vector file: https://github.com/peterrosell/svg2android/blob/gh-pages/scale_logo.xml

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
