### ISSUE TITLE
Add support for gradients

### ISSUE THREAD

**Issue by alexjlockwood** [inloop/svg2android#72]

**Comment by martinbonnin** [comment]
+1 to that. Any pointers where to start/how complicated it would be to make it work ?

**Comment by yuraj11** [comment]
I was not paying too much attention to this feature because Gradients are still supported from API 24+ only - https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html (check fillColor and strokeColor attribute).

**Comment by winsock** [comment]
I have done a basic implementation of this feature in PR #93

**Comment by yuraj11** [comment]
As this tool is deprecated please use https://developer.android.com/studio/write/vector-asset-studio#svg which can do this job better :)
