### ISSUE TITLE
Android svgs do not support scientific notation

### ISSUE THREAD

**Issue by RicardoTrindade** [inloop/svg2android#79]
When converting from and svg to xml code the output contained a really small value 

`<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

    <path
        android:fillColor="#FC59D8"
        android:fillAlpha="0"
        android:strokeWidth="1"
        android:pathData="M -4.54747351e-13 0 H 24 V 24 H -4.54747351e-13 V 0 Z" />
    <path
        android:fillColor="#041520"
        android:strokeWidth="1"
        android:pathData="M9.0583115,11.5602833 C9.81198399,12.9461192 10.885289,14 12,14 `

 The value is -4.4e-13.
 Turns out that Android does not support values with scientific notation and had to change these values to 0.
This issue was already here but was closed though

**Comment by RicardoTrindade** [comment]
[icon.zip](https://github.com/inloop/svg2android/files/963902/icon.zip)
 I'm also attaching the original svg file and its converted file as I am not being able to paste the entire xml code here

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
