### ISSUE TITLE
Bake transforms into path (experimental) messes icon position up

### ISSUE THREAD

**Issue by vanniktech** [inloop/svg2android#80]
### Input Icon

```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <g fill="none" fill-rule="evenodd" transform="translate(-5 -4)">
        <path d="M5 4h24v24H5z"/>
        <circle cx="17" cy="16" r="5" fill="#FB4754"/>
        <g stroke="#FB4754" stroke-linecap="square" stroke-width="1.5">
            <path d="M6.629 15.765h2.828M24.543 15.765h2.828"/>
            <g>
                <path d="M17 26.371v-2.828M17 8.457V5.63"/>
            </g>
            <g>
                <path d="M9.5 23.167l2-2M22.167 10.5l2-2"/>
                <g>
                    <path d="M24.334 23.333l-2-2M11.667 10.666l-2-2"/>
                </g>
            </g>
        </g>
    </g>
</svg>
```

### Works without `Bake transforms into path`

When I convert it using those options:

![screen shot 2017-05-15 at 12 39 35](https://cloud.githubusercontent.com/assets/5759366/26054055/95c537ee-396b-11e7-9534-78a68995ea67.png)

The image will be transformed correctly.

![screen shot 2017-05-15 at 12 40 13](https://cloud.githubusercontent.com/assets/5759366/26054153/e065e2c6-396b-11e7-8f75-e460d00f48d1.png)

### Does not work with `Bake transforms into path`

However when I activate `Bake transforms into path`:

![screen shot 2017-05-15 at 12 40 40](https://cloud.githubusercontent.com/assets/5759366/26054089/b82300c8-396b-11e7-9478-522e13b89c09.png)

The image will not be transformed correctly and is not centered:

![screen shot 2017-05-15 at 12 41 03](https://cloud.githubusercontent.com/assets/5759366/26054124/ca6d8686-396b-11e7-9274-d1833b9033d2.png)

**Comment by theBlbDan** [comment]
I ran into a condition where I had some &lt;rect />'s with a transform that included translate and rotation.
I found in the [VectorDrawable](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html) docs that some transforms exists in the group tag.  It might be worth fixing up svg2android for these.

**Comment by vanniktech** [comment]
Gentle bump on this.

**Comment by vanniktech** [comment]
@yuraj11 is this project still being maintained? Otherwise I'd use the tools from the android folks instead.

**Comment by theBlbDan** [comment]
What tools does Google have?

**Comment by yuraj11** [comment]
It is not deprecated but also not active because I do not have that much free time to fix all the issues. SVG format is too complex and some bug fixes could introduce another bugs. Have you tried the official Android Studio svg import dialog https://developer.android.com/studio/write/vector-asset-studio.html ?

**Comment by vanniktech** [comment]
That's also the one I meant with Google tools.

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
