### ISSUE TITLE
Issue converting this SVG file

### ISSUE THREAD

**Issue by MRezaNasirloo** [inloop/svg2android#85]
It's the TMDB logo it only shows `TM`
[ic_tmdb_stacked-green.zip](https://github.com/inloop/svg2android/files/1146776/ic_tmdb_stacked-green.zip)

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
