### ISSUE TITLE
Prepend 0

### ISSUE THREAD

**Issue by PaulWoitaschek** [inloop/svg2android#89]
For the generated files, lint shows me a warning that numbers that start with a `.`, i.e. (`.5`) can crash on some devices. Instead it suggests to prepend a `0`.
I think this is something this library could perfectly do.

![zero](https://user-images.githubusercontent.com/743462/30428858-75c1d6d8-9955-11e7-86de-ea3153fdc66b.png)

**Comment by SjoerdvGestel** [comment]
would love to see this fixed!

I've made a quick regexp for find and replace in Android studio to fix the issue manually:

- search:` ([^\d])\.`
- replace: `$10.`

> note: its not perfect, it will replace in  xmlns:android="http://schemas.android.com/apk/res/android" but just be aware of that and restore it after replacing all 
**
![image](https://user-images.githubusercontent.com/1597644/34562092-244a4a06-f14d-11e7-92d9-e02c427627a2.png)
**

**Comment by yuraj11** [comment]
Thanks, fixed.
