### ISSUE TITLE
Minor conversion issues

### ISSUE THREAD

**Issue by gerrysc** [inloop/svg2android#91]
[converted.zip](https://github.com/inloop/svg2android/files/1384954/converted.zip)
[modified.zip](https://github.com/inloop/svg2android/files/1384955/modified.zip)
[svg.zip](https://github.com/inloop/svg2android/files/1384956/svg.zip)

I have three .svg files generated from Inkscape with text converted to path i.e. Path/Object to Path. (svg.zip). After conversion (converted.zip) the vectors were distorted in different ways in Android Studio 2.1.1.  (I received a warning about scientific notation but this turned out not to be a problem).  I found that, by tweaking the paths on all three vectors, in different ways, I could get them to display correctly (modified.zip);

I very much appreciate the conversion service you provide.

**Comment by gerrysc** [comment]
While the modified icons were rendered correctly in Android Studio, I found that one of them crashed the emulator for Android 5.0: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2 at                                                             android.util.PathParser$PathDataNode.addCommand(PathParser.java:370).
This was, of course, due to scientific notation.  When altered to fixed point notation, the problem was solved.

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
