### ISSUE TITLE
my svg does not convert correctly...

### ISSUE THREAD

**Issue by freerider7777** [inloop/svg2android#97]
https://drive.google.com/open?id=1Qsu-GBlHRPEQxeXGMxzgHYIVIgcTPFX9

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
