### ISSUE TITLE
Wrong Convert of Star

### ISSUE THREAD

**Issue by valeriyo** [inloop/svg2android#99]
The gold star (https://upload.wikimedia.org/wikipedia/commons/2/29/Gold_Star.svg) converted to something that's broken:

```
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="240dp"
    android:viewportHeight="240"
    android:viewportWidth="240"
    android:width="240dp">

  <path
      android:fillColor="#f5d315"
      android:pathData="M48,234 73-226 73,226-192-140h238z"/>

</vector>
```

Changing first "M" to lowercase "m" seems to fix it - so that it looks correct like a star.

**Comment by yuraj11** [comment]
As this tool is deprecated and behind the official AS solution in term of conversion - you can check https://developer.android.com/studio/write/vector-asset-studio#svg - I have tried converting this SVG and It renders correctly using AS Vector Asset Studio.
